/**
 * Unified Battle API
 * POST /api/unified-battles - Create or manage battles
 * GET /api/unified-battles - List battles
 */

import { NextRequest, NextResponse } from 'next/server';
import {
  createUnifiedBattle,
  getAllUnifiedBattles,
  getUnifiedBattle,
  initializeUnifiedBattleSystem,
  PRESET_FACTIONS
} from '@/lib/unifiedBattleStorage';
import { PRESET_PERSONALITIES } from '@/lib/agents/personality';
import type { CreateBattleRequest, BattleFilter } from '@/lib/unifiedBattle';

// Initialize system on first load
let systemInitialized = false;

function ensureSystemInitialized() {
  if (!systemInitialized) {
    initializeUnifiedBattleSystem();
    systemInitialized = true;
  }
}

export async function POST(request: NextRequest) {
  ensureSystemInitialized();

  try {
    const body = await request.json();
    const { action } = body;

    if (action === 'create') {
      // Create new battle
      const createRequest: CreateBattleRequest = {
        mode: body.mode || 'ava',
        topic: body.topic,
        description: body.description,
        participantA: body.participantA,
        participantB: body.participantB,
        factionA: body.factionA,
        factionB: body.factionB,
        rounds: body.rounds || 3,
        roundDuration: body.roundDuration || 90,
        creatorUserId: body.creatorUserId,
        autoGenerated: body.autoGenerated || false,
        tags: body.tags || []
      };

      const controller = createUnifiedBattle(createRequest);
      const battle = controller.getState();

      return NextResponse.json({
        success: true,
        message: 'Battle created successfully',
        battle: {
          id: battle.id,
          mode: battle.mode,
          topic: battle.topic,
          description: battle.description,
          participantA: {
            type: battle.participantA.type,
            id: battle.participantA.id,
            name: battle.participantA.name,
            faction: battle.participantA.faction
          },
          participantB: {
            type: battle.participantB.type,
            id: battle.participantB.id,
            name: battle.participantB.name,
            faction: battle.participantB.faction
          },
          status: battle.status,
          rounds: battle.rounds,
          createdAt: battle.createdAt
        }
      });
    } else if (action === 'start') {
      // Start existing battle
      const { battleId } = body;

      if (!battleId) {
        return NextResponse.json(
          { error: 'battleId is required' },
          { status: 400 }
        );
      }

      const controller = getUnifiedBattle(battleId);
      if (!controller) {
        return NextResponse.json(
          { error: 'Battle not found' },
          { status: 404 }
        );
      }

      // Start battle asynchronously
      controller.start().catch(error => {
        console.error(`[API] Failed to start battle ${battleId}:`, error);
      });

      return NextResponse.json({
        success: true,
        message: 'Battle started'
      });
    } else {
      return NextResponse.json(
        { error: 'Invalid action. Use "create" or "start"' },
        { status: 400 }
      );
    }
  } catch (error) {
    console.error('[API] Unified battles POST error:', error);
    return NextResponse.json(
      { error: 'Internal server error' },
      { status: 500 }
    );
  }
}

export async function GET(request: NextRequest) {
  ensureSystemInitialized();

  try {
    const { searchParams } = new URL(request.url);
    const mode = searchParams.get('mode') as any;
    const status = searchParams.get('status') as any;
    const featured = searchParams.get('featured');
    const participantId = searchParams.get('participantId');
    const tags = searchParams.get('tags');

    const filter: BattleFilter = {
      mode: mode || 'all',
      status: status || 'all',
      featured: featured === 'true' ? true : featured === 'false' ? false : undefined,
      participantId: participantId || undefined,
      tags: tags ? tags.split(',') : undefined
    };

    const battles = getAllUnifiedBattles(filter);

    return NextResponse.json({
      success: true,
      battles: battles.map(battle => ({
        id: battle.id,
        mode: battle.mode,
        topic: battle.topic,
        description: battle.description,
        participantA: {
          type: battle.participantA.type,
          id: battle.participantA.id,
          name: battle.participantA.name,
          faction: battle.participantA.faction
        },
        participantB: {
          type: battle.participantB.type,
          id: battle.participantB.id,
          name: battle.participantB.name,
          faction: battle.participantB.faction
        },
        status: battle.status,
        currentRound: battle.currentRound,
        totalRounds: battle.rounds,
        scoreboard: battle.scoreboard,
        bettingPool: battle.bettingPool,
        mintedNFTs: battle.mintedNFTs,
        createdAt: battle.createdAt,
        startedAt: battle.startedAt,
        endedAt: battle.endedAt,
        winner: battle.winner,
        featured: battle.featured,
        autoGenerated: battle.autoGenerated,
        tags: battle.tags
      })),
      count: battles.length,
      presets: {
        factions: Object.values(PRESET_FACTIONS),
        agents: PRESET_PERSONALITIES.map(p => ({
          id: p.id,
          name: p.name,
          type: p.type,
          description: `${p.type} personality - Risk: ${p.riskTolerance}, Creativity: ${p.creativityBias}`
        }))
      }
    });
  } catch (error) {
    console.error('[API] Unified battles GET error:', error);
    return NextResponse.json(
      { error: 'Internal server error' },
      { status: 500 }
    );
  }
}
