/**
 * Unified Arena - Battle Hall
 * Shows all types of battles: PvP, P vs Agent, Agent vs Agent
 * Allows users to create custom battles
 */

'use client';

import { FC, useState, useEffect } from 'react';
import Link from 'next/link';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { CreateBattleModal } from '@/components/CreateBattleModal';
import {
  Swords, Clock, Users, TrendingUp, Play, Eye, Bot, Sparkles,
  Trophy, Plus, Zap, Shield
} from 'lucide-react';

interface UnifiedBattle {
  id: string;
  mode: 'pvp' | 'pva' | 'ava';
  topic: string;
  description: string;
  status: 'pending' | 'active' | 'ended';
  currentRound: number;
  totalRounds: number;
  participantA: {
    type: 'user' | 'agent';
    name: string;
    faction: {
      name: string;
      color: string;
      icon: string;
    };
  };
  participantB: {
    type: 'user' | 'agent';
    name: string;
    faction: {
      name: string;
      color: string;
      icon: string;
    };
  };
  scoreboard: {
    participantA: { totalVotes: number; roundsWon: number };
    participantB: { totalVotes: number; roundsWon: number };
  };
  bettingPool: {
    totalOnA: number;
    totalOnB: number;
  };
  mintedNFTs: {
    factionA: number;
    factionB: number;
  };
  startedAt?: string;
  endedAt?: string;
  winner?: 'A' | 'B' | 'draw';
  featured?: boolean;
  autoGenerated?: boolean;
  tags?: string[];
}

export default function UnifiedArenaPage() {
  const [battles, setBattles] = useState<UnifiedBattle[]>([]);
  const [loading, setLoading] = useState(true);
  const [filter, setFilter] = useState<'all' | 'active' | 'ended'>('all');
  const [modeFilter, setModeFilter] = useState<'all' | 'pvp' | 'pva' | 'ava'>('all');
  const [showCreateModal, setShowCreateModal] = useState(false);
  const [userId, setUserId] = useState('');
  const [presets, setPresets] = useState<any>(null);

  useEffect(() => {
    // Get or create user ID
    let id = localStorage.getItem('timepics_user_id');
    if (!id) {
      id = `user-${Date.now()}-${Math.random().toString(36).substr(2, 9)}`;
      localStorage.setItem('timepics_user_id', id);
    }
    setUserId(id);

    fetchBattles();
    const interval = setInterval(fetchBattles, 5000);
    return () => clearInterval(interval);
  }, []);

  const fetchBattles = async () => {
    try {
      const response = await fetch('/api/unified-battles');
      const data = await response.json();
      if (data.success) {
        setBattles(data.battles);
        setPresets(data.presets);
      }
    } catch (error) {
      console.error('Failed to fetch battles:', error);
    } finally {
      setLoading(false);
    }
  };

  const filteredBattles = battles.filter(battle => {
    if (filter !== 'all' && battle.status !== filter) return false;
    if (modeFilter !== 'all' && battle.mode !== modeFilter) return false;
    return true;
  });

  const activeBattles = battles.filter(b => b.status === 'active');
  const endedBattles = battles.filter(b => b.status === 'ended');

  const getModeIcon = (mode: string) => {
    if (mode === 'pvp') return <Users className="w-4 h-4" />;
    if (mode === 'pva') return <Swords className="w-4 h-4" />;
    return <Bot className="w-4 h-4" />;
  };

  const getModeLabel = (mode: string) => {
    if (mode === 'pvp') return 'PvP';
    if (mode === 'pva') return 'P vs Agent';
    return 'Agent vs Agent';
  };

  const getModeColor = (mode: string) => {
    if (mode === 'pvp') return 'bg-blue-600';
    if (mode === 'pva') return 'bg-purple-600';
    return 'bg-green-600';
  };

  const handleBattleCreated = (battleId: string) => {
    fetchBattles();
    // Optionally navigate to battle
    window.location.href = `/unified-arena/${battleId}`;
  };

  return (
    <div className="min-h-screen bg-gradient-to-b from-gray-900 via-purple-900/20 to-gray-900 text-white">
      <div className="container mx-auto px-4 py-8">
        {/* Header */}
        <div className="mb-8">
          <div className="flex items-center justify-between mb-4">
            <div className="flex items-center gap-3">
              <Swords className="w-10 h-10 text-purple-400" />
              <div>
                <h1 className="text-4xl font-bold bg-gradient-to-r from-purple-400 to-pink-400 bg-clip-text text-transparent">
                  Timeline War
                </h1>
                <p className="text-gray-400 text-sm mt-1">
                  Watch, participate, or create your own timeline battles
                </p>
              </div>
            </div>
            <Button
              onClick={() => setShowCreateModal(true)}
              className="bg-gradient-to-r from-purple-600 to-pink-600 hover:from-purple-700 hover:to-pink-700"
              size="lg"
            >
              <Plus className="w-5 h-5 mr-2" />
              Create Battle
            </Button>
          </div>
        </div>

        {/* Stats */}
        <div className="grid grid-cols-1 md:grid-cols-4 gap-4 mb-8">
          <Card className="bg-gray-800/50 border-gray-700">
            <CardContent className="pt-6">
              <div className="flex items-center justify-between">
                <div>
                  <p className="text-sm text-gray-400">Active Now</p>
                  <p className="text-3xl font-bold text-purple-400">{activeBattles.length}</p>
                </div>
                <Play className="w-8 h-8 text-purple-400" />
              </div>
            </CardContent>
          </Card>

          <Card className="bg-gray-800/50 border-gray-700">
            <CardContent className="pt-6">
              <div className="flex items-center justify-between">
                <div>
                  <p className="text-sm text-gray-400">Total Battles</p>
                  <p className="text-3xl font-bold text-blue-400">{battles.length}</p>
                </div>
                <Swords className="w-8 h-8 text-blue-400" />
              </div>
            </CardContent>
          </Card>

          <Card className="bg-gray-800/50 border-gray-700">
            <CardContent className="pt-6">
              <div className="flex items-center justify-between">
                <div>
                  <p className="text-sm text-gray-400">Completed</p>
                  <p className="text-3xl font-bold text-green-400">{endedBattles.length}</p>
                </div>
                <Trophy className="w-8 h-8 text-green-400" />
              </div>
            </CardContent>
          </Card>

          <Card className="bg-gray-800/50 border-gray-700">
            <CardContent className="pt-6">
              <div className="flex items-center justify-between">
                <div>
                  <p className="text-sm text-gray-400">NFTs Minted</p>
                  <p className="text-3xl font-bold text-yellow-400">
                    {battles.reduce((sum, b) => sum + b.mintedNFTs.factionA + b.mintedNFTs.factionB, 0)}
                  </p>
                </div>
                <Sparkles className="w-8 h-8 text-yellow-400" />
              </div>
            </CardContent>
          </Card>
        </div>

        {/* Filters */}
        <div className="mb-6 flex gap-4 items-center">
          <div>
            <label className="text-sm text-gray-400 mr-2">Status:</label>
            <select
              value={filter}
              onChange={e => setFilter(e.target.value as any)}
              className="bg-gray-800 border border-gray-700 rounded px-3 py-1"
            >
              <option value="all">All</option>
              <option value="active">Active</option>
              <option value="ended">Ended</option>
            </select>
          </div>

          <div>
            <label className="text-sm text-gray-400 mr-2">Mode:</label>
            <select
              value={modeFilter}
              onChange={e => setModeFilter(e.target.value as any)}
              className="bg-gray-800 border border-gray-700 rounded px-3 py-1"
            >
              <option value="all">All Modes</option>
              <option value="ava">Agent vs Agent</option>
              <option value="pva">Player vs Agent</option>
              <option value="pvp">Player vs Player</option>
            </select>
          </div>

          <div className="text-sm text-gray-500 ml-auto">
            Showing {filteredBattles.length} battles
          </div>
        </div>

        {/* Battle List */}
        {loading ? (
          <div className="text-center py-12">
            <p className="text-gray-400">Loading battles...</p>
          </div>
        ) : filteredBattles.length === 0 ? (
          <Card className="bg-gray-800/50 border-gray-700">
            <CardContent className="py-12 text-center">
              <Swords className="w-16 h-16 text-gray-600 mx-auto mb-4" />
              <p className="text-gray-400 text-lg mb-2">No battles found</p>
              <p className="text-gray-500 text-sm mb-4">
                {modeFilter === 'all'
                  ? 'Be the first to create a battle!'
                  : `No ${getModeLabel(modeFilter)} battles available`}
              </p>
              <Button
                onClick={() => setShowCreateModal(true)}
                className="bg-purple-600 hover:bg-purple-700"
              >
                <Plus className="w-4 h-4 mr-2" />
                Create Battle
              </Button>
            </CardContent>
          </Card>
        ) : (
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
            {filteredBattles.map(battle => (
              <Card
                key={battle.id}
                className="bg-gray-800/50 border-gray-700 hover:border-purple-500/50 transition-all"
              >
                <CardHeader>
                  <div className="flex items-start justify-between mb-2">
                    <div className="flex-1">
                      <div className="flex items-center gap-2 mb-2">
                        <Badge className={getModeColor(battle.mode)}>
                          {getModeIcon(battle.mode)}
                          <span className="ml-1">{getModeLabel(battle.mode)}</span>
                        </Badge>
                        {battle.status === 'active' && (
                          <Badge className="bg-green-600 animate-pulse">
                            <Play className="w-3 h-3 mr-1" />
                            LIVE
                          </Badge>
                        )}
                        {battle.featured && (
                          <Badge variant="outline" className="border-yellow-400 text-yellow-400">
                            ⭐ Featured
                          </Badge>
                        )}
                        {battle.autoGenerated && (
                          <Badge variant="outline" className="text-xs">
                            <Bot className="w-3 h-3 mr-1" />
                            Auto
                          </Badge>
                        )}
                      </div>
                      <CardTitle className="text-xl mb-1">{battle.topic}</CardTitle>
                      {battle.status === 'active' && (
                        <p className="text-sm text-gray-400">
                          Round {battle.currentRound}/{battle.totalRounds}
                        </p>
                      )}
                    </div>
                  </div>
                </CardHeader>

                <CardContent>
                  {/* Participants */}
                  <div className="grid grid-cols-2 gap-4 mb-4">
                    {/* Participant A */}
                    <div
                      className="p-3 rounded-lg border"
                      style={{
                        borderColor: battle.participantA.faction.color,
                        background: `${battle.participantA.faction.color}10`
                      }}
                    >
                      <div className="flex items-center gap-2 mb-2">
                        <span className="text-2xl">{battle.participantA.faction.icon}</span>
                        <div className="flex-1 min-w-0">
                          <p className="font-medium text-sm truncate">
                            {battle.participantA.name}
                          </p>
                          <p className="text-xs text-gray-400 truncate">
                            {battle.participantA.faction.name}
                          </p>
                        </div>
                      </div>
                      {battle.status !== 'pending' && (
                        <div className="text-sm">
                          <p className="text-gray-400">
                            {battle.scoreboard.participantA.totalVotes} votes
                          </p>
                          <p className="text-gray-400">
                            {battle.scoreboard.participantA.roundsWon} rounds won
                          </p>
                        </div>
                      )}
                    </div>

                    {/* Participant B */}
                    <div
                      className="p-3 rounded-lg border"
                      style={{
                        borderColor: battle.participantB.faction.color,
                        background: `${battle.participantB.faction.color}10`
                      }}
                    >
                      <div className="flex items-center gap-2 mb-2">
                        <span className="text-2xl">{battle.participantB.faction.icon}</span>
                        <div className="flex-1 min-w-0">
                          <p className="font-medium text-sm truncate">
                            {battle.participantB.name}
                          </p>
                          <p className="text-xs text-gray-400 truncate">
                            {battle.participantB.faction.name}
                          </p>
                        </div>
                      </div>
                      {battle.status !== 'pending' && (
                        <div className="text-sm">
                          <p className="text-gray-400">
                            {battle.scoreboard.participantB.totalVotes} votes
                          </p>
                          <p className="text-gray-400">
                            {battle.scoreboard.participantB.roundsWon} rounds won
                          </p>
                        </div>
                      )}
                    </div>
                  </div>

                  {/* Stats */}
                  <div className="flex items-center justify-between text-sm text-gray-400 mb-4">
                    <div className="flex items-center gap-1">
                      <Shield className="w-4 h-4" />
                      <span>{battle.mintedNFTs.factionA + battle.mintedNFTs.factionB} NFTs</span>
                    </div>
                    <div className="flex items-center gap-1">
                      <Zap className="w-4 h-4" />
                      <span>{battle.bettingPool.totalOnA + battle.bettingPool.totalOnB} tokens</span>
                    </div>
                  </div>

                  {/* Winner */}
                  {battle.status === 'ended' && battle.winner && (
                    <div className="mb-4 p-3 bg-yellow-900/20 border border-yellow-700/50 rounded-lg">
                      <div className="flex items-center gap-2">
                        <Trophy className="w-5 h-5 text-yellow-400" />
                        <span className="font-medium">
                          Winner:{' '}
                          {battle.winner === 'A'
                            ? battle.participantA.name
                            : battle.winner === 'B'
                            ? battle.participantB.name
                            : 'Draw'}
                        </span>
                      </div>
                    </div>
                  )}

                  {/* Action Button */}
                  <Link href={`/unified-arena/${battle.id}`}>
                    <Button className="w-full" variant={battle.status === 'active' ? 'default' : 'outline'}>
                      {battle.status === 'active' ? (
                        <>
                          <Eye className="w-4 h-4 mr-2" />
                          Watch Live
                        </>
                      ) : battle.status === 'pending' ? (
                        <>
                          <Clock className="w-4 h-4 mr-2" />
                          Starting Soon
                        </>
                      ) : (
                        <>
                          <TrendingUp className="w-4 h-4 mr-2" />
                          View Results
                        </>
                      )}
                    </Button>
                  </Link>
                </CardContent>
              </Card>
            ))}
          </div>
        )}
      </div>

      {/* Create Battle Modal */}
      <CreateBattleModal
        open={showCreateModal}
        onOpenChange={setShowCreateModal}
        userId={userId}
        onBattleCreated={handleBattleCreated}
        presets={presets}
      />
    </div>
  );
}
