/**
 * Unified Battle System
 * Supports: PvP, P vs Agent, Agent vs Agent
 * Replaces both old battle system and timeline wars
 */

import { TimelineAgent, type AgentOutput } from './agents/TimelineAgent';

export type BattleMode = 'pvp' | 'pva' | 'ava';  // Player vs Player, Player vs Agent, Agent vs Agent
export type BattleStatus = 'pending' | 'active' | 'ended' | 'cancelled';
export type ParticipantType = 'user' | 'agent';

/**
 * Unified Battle Participant
 * Can be either a user or an agent
 */
export interface BattleParticipant {
  type: ParticipantType;
  id: string;
  name: string;

  // For users
  userId?: string;

  // For agents
  agent?: TimelineAgent;
  personality?: string;

  // Faction info
  faction: BattleFaction;
}

export interface BattleFaction {
  id: string;
  name: string;
  theme: string;
  description: string;
  color: string;
  icon: string;
}

/**
 * Battle Creation Source
 */
export type BattleCreator =
  | { type: 'user'; userId: string }
  | { type: 'agent'; agentId: string; trigger: 'timeline-logic' | 'scheduled' | 'manual' };

/**
 * Unified Battle
 */
export interface UnifiedBattle {
  id: string;
  mode: BattleMode;

  // Battle info
  topic: string;
  description: string;

  // Participants
  participantA: BattleParticipant;
  participantB: BattleParticipant;

  // Creation info
  creator: BattleCreator;
  createdAt: Date;

  // Battle settings
  rounds: number;              // 3-5 rounds
  roundDuration: number;       // 90 seconds per round

  // State
  status: BattleStatus;
  currentRound: number;
  roundResults: BattleRoundResult[];

  // Timestamps
  startedAt?: Date;
  endedAt?: Date;

  // Scoreboard
  scoreboard: {
    participantA: {
      roundScores: number[];    // Votes/points per round
      totalVotes: number;
      roundsWon: number;
    };
    participantB: {
      roundScores: number[];
      totalVotes: number;
      roundsWon: number;
    };
  };

  // Betting & NFT
  bettingPool: {
    totalOnA: number;
    totalOnB: number;
  };

  mintedNFTs: {
    factionA: number;
    factionB: number;
  };

  // Odds history (for dynamic odds)
  oddsHistory?: Array<{
    timestamp: number;
    oddsA: number;
    oddsB: number;
    totalBetsOnA: number;
    totalBetsOnB: number;
  }>;

  // Winner
  winner?: 'A' | 'B' | 'draw';

  // Metadata
  tags?: string[];             // For filtering and discovery
  featured?: boolean;          // Highlighted in arena
  autoGenerated?: boolean;     // Generated by agent
}

/**
 * Round result for unified battle
 */
export interface BattleRoundResult {
  roundNumber: number;

  // Participant A output
  participantA: {
    type: ParticipantType;
    output?: AgentOutput;      // For agents
    imageUrl: string;
    userPrompt?: string;       // For users
    votes: number;
  };

  // Participant B output
  participantB: {
    type: ParticipantType;
    output?: AgentOutput;
    imageUrl: string;
    userPrompt?: string;
    votes: number;
  };

  winner: 'A' | 'B' | 'draw';
  startedAt: Date;
  endedAt: Date;
}

/**
 * Battle creation request
 */
export interface CreateBattleRequest {
  mode: BattleMode;
  topic: string;
  description: string;

  // Participant A
  participantA: {
    type: ParticipantType;
    userId?: string;
    agentId?: string;           // Preset agent personality ID
    factionId?: string;         // Optional: use preset faction
  };

  // Participant B
  participantB: {
    type: ParticipantType;
    userId?: string;
    agentId?: string;
    factionId?: string;
  };

  // Factions (if not using preset)
  factionA?: BattleFaction;
  factionB?: BattleFaction;

  // Settings
  rounds?: number;              // Default: 3
  roundDuration?: number;       // Default: 90

  // Creator
  creatorUserId?: string;       // If created by user
  autoGenerated?: boolean;      // If generated by agent
  tags?: string[];
}

/**
 * Battle filter for arena listing
 */
export interface BattleFilter {
  mode?: BattleMode | 'all';
  status?: BattleStatus | 'all';
  tags?: string[];
  featured?: boolean;
  participantId?: string;       // Show battles involving this user/agent
}

/**
 * Agent auto-generation config
 */
export interface AutoGenerationConfig {
  enabled: boolean;
  interval: number;             // Minutes between generations
  topicsPool: string[];         // Possible battle topics
  minActiveBattles: number;     // Keep this many active battles
  maxActiveBattles: number;
}

export const DEFAULT_AUTO_GENERATION_CONFIG: AutoGenerationConfig = {
  enabled: true,
  interval: 10,                 // Every 10 minutes
  topicsPool: [
    "What if Rome Never Fell?",
    "What if the Internet Was Invented in 1950?",
    "What if Humans Colonized Mars in 2000?",
    "What if AI Achieved Consciousness in 1990?",
    "What if Climate Change Was Reversed?",
    "What if Nuclear Fusion Succeeded in 1980?",
    "What if Dinosaurs Never Went Extinct?",
    "What if Time Travel Was Discovered Tomorrow?"
  ],
  minActiveBattles: 2,
  maxActiveBattles: 5
};
