/**
 * Unified Battle State API
 * GET /api/unified-battles/[id]/state - Get battle state
 */

import { NextRequest, NextResponse } from 'next/server';
import { getUnifiedBattle } from '@/lib/unifiedBattleStorage';

export async function GET(
  request: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  try {
    const { id: battleId } = await params;

    const controller = getUnifiedBattle(battleId);
    if (!controller) {
      return NextResponse.json(
        { error: 'Battle not found' },
        { status: 404 }
      );
    }

    const battle = controller.getState();
    const currentVotes = controller.getCurrentRoundVotes();
    const oddsHistory = controller.getOddsHistory();

    return NextResponse.json({
      success: true,
      battle: {
        id: battle.id,
        mode: battle.mode,
        topic: battle.topic,
        description: battle.description,
        status: battle.status,
        currentRound: battle.currentRound,
        totalRounds: battle.rounds,
        roundDuration: battle.roundDuration,
        participantA: {
          type: battle.participantA.type,
          id: battle.participantA.id,
          name: battle.participantA.name,
          faction: battle.participantA.faction,
          personality: battle.participantA.personality
        },
        participantB: {
          type: battle.participantB.type,
          id: battle.participantB.id,
          name: battle.participantB.name,
          faction: battle.participantB.faction,
          personality: battle.participantB.personality
        },
        scoreboard: battle.scoreboard,
        roundResults: battle.roundResults,
        currentRoundVotes: currentVotes,
        bettingPool: battle.bettingPool,
        mintedNFTs: battle.mintedNFTs,
        oddsHistory,
        startedAt: battle.startedAt,
        endedAt: battle.endedAt,
        winner: battle.winner,
        creator: battle.creator,
        featured: battle.featured,
        autoGenerated: battle.autoGenerated,
        tags: battle.tags
      }
    });
  } catch (error) {
    console.error('[API] Get unified battle state error:', error);
    return NextResponse.json(
      { error: 'Internal server error' },
      { status: 500 }
    );
  }
}
